import Link from "next/link"
import type {Metadata} from 'next'
import styles from './about.module.css'


export const metadata: Metadata = {
  title: 'Welcome My About Page',
  description: 'Generated by create next app',
  
}


export default function About() {
  // throw new Error('Not Working')
  return (
    <div>
        <h1>My About page</h1>
        <button className={styles.btn}>
            <Link href='/'>Home</Link>
        </button>
    </div>
  )
}
